/**
 * Trial-grant and manual-adjustment provenance repository (`WP-COM-03`;
 * design §9, §10.3, §20). INSERT and READ only: the database rejects UPDATE,
 * DELETE and TRUNCATE, and requires each row to be backed by the matching
 * ledger entry. Rows are written together with that ledger entry (which is
 * posted through `postCommercialLedgerEntry`); nothing here touches the
 * account counters.
 */

import type { PlatformPostgresPool } from "../../../infrastructure/postgres/postgresPool";
import type { PlatformPostgresTransaction } from "../../../infrastructure/postgres/postgresTransaction";
import type {
  CommercialManualAdjustment,
  CommercialTrialGrant,
  CommercialTrialGrantKind,
} from "../models/commercialAdministration";

type Queryable = Pick<PlatformPostgresPool, "query"> | PlatformPostgresTransaction;

type GrantRow = {
  id: string;
  business_id: string;
  kind: CommercialTrialGrantKind;
  units: number;
  granted_by: string;
  granted_at: Date;
  reason_code: string | null;
  reason_text: string;
  reference: string;
  ledger_entry_id: string;
  idempotency_key: string;
};

const GRANT_COLUMNS = `id, business_id, kind, units, granted_by, granted_at, reason_code,
  reason_text, reference, ledger_entry_id, idempotency_key`;

function mapGrant(row: GrantRow): CommercialTrialGrant {
  return {
    id: row.id,
    businessId: row.business_id,
    kind: row.kind,
    units: row.units,
    grantedBy: row.granted_by,
    grantedAt: row.granted_at,
    reasonCode: row.reason_code,
    reasonText: row.reason_text,
    reference: row.reference,
    ledgerEntryId: row.ledger_entry_id,
    idempotencyKey: row.idempotency_key,
  };
}

export type InsertTrialGrantParams = {
  /** Generated by the caller: the ledger entry's source reference already names it. */
  readonly id: string;
  readonly businessId: string;
  readonly units: number;
  readonly grantedBy: string;
  readonly reasonCode?: string;
  readonly reasonText: string;
  readonly reference: string;
  readonly ledgerEntryId: string;
  readonly idempotencyKey: string;
  readonly correlationId: string;
};

export async function insertTrialGrant(
  tx: PlatformPostgresTransaction,
  p: InsertTrialGrantParams,
): Promise<CommercialTrialGrant> {
  const result = await tx.query<GrantRow>(
    `INSERT INTO commercial_trial_grants
       (id, business_id, kind, units, granted_by, reason_code, reason_text, reference,
        ledger_entry_id, idempotency_key, correlation_id)
     VALUES ($1,$2,'initial',$3,$4,$5,$6,$7,$8,$9,$10)
     RETURNING ${GRANT_COLUMNS}`,
    [
      p.id,
      p.businessId,
      p.units,
      p.grantedBy,
      p.reasonCode ?? null,
      p.reasonText,
      p.reference,
      p.ledgerEntryId,
      p.idempotencyKey,
      p.correlationId,
    ],
  );
  return mapGrant(result.rows[0]);
}

/** Every grant of a Business, oldest first. Informational (design §9): never blocks a new grant. */
export async function listTrialGrants(
  db: Queryable,
  businessId: string,
): Promise<CommercialTrialGrant[]> {
  const result = await db.query<GrantRow>(
    `SELECT ${GRANT_COLUMNS} FROM commercial_trial_grants
      WHERE business_id = $1 ORDER BY granted_at, id`,
    [businessId],
  );
  return result.rows.map(mapGrant);
}

type AdjustmentRow = {
  id: string;
  business_id: string;
  bucket: "trial" | "paid";
  units_delta: number;
  reason_code: string | null;
  reason_text: string;
  reference: string;
  created_by: string;
  created_at: Date;
  ledger_entry_id: string;
  idempotency_key: string;
};

const ADJUSTMENT_COLUMNS = `id, business_id, bucket, units_delta, reason_code, reason_text,
  reference, created_by, created_at, ledger_entry_id, idempotency_key`;

function mapAdjustment(row: AdjustmentRow): CommercialManualAdjustment {
  return {
    id: row.id,
    businessId: row.business_id,
    bucket: row.bucket,
    unitsDelta: row.units_delta,
    reasonCode: row.reason_code,
    reasonText: row.reason_text,
    reference: row.reference,
    createdBy: row.created_by,
    createdAt: row.created_at,
    ledgerEntryId: row.ledger_entry_id,
    idempotencyKey: row.idempotency_key,
  };
}

export type InsertManualAdjustmentParams = {
  readonly id: string;
  readonly businessId: string;
  readonly bucket: "trial" | "paid";
  readonly unitsDelta: number;
  readonly reasonCode?: string;
  readonly reasonText: string;
  readonly reference: string;
  readonly createdBy: string;
  readonly ledgerEntryId: string;
  readonly idempotencyKey: string;
  readonly correlationId: string;
};

export async function insertManualAdjustment(
  tx: PlatformPostgresTransaction,
  p: InsertManualAdjustmentParams,
): Promise<CommercialManualAdjustment> {
  const result = await tx.query<AdjustmentRow>(
    `INSERT INTO commercial_manual_adjustments
       (id, business_id, bucket, units_delta, reason_code, reason_text, reference, created_by,
        ledger_entry_id, idempotency_key, correlation_id)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
     RETURNING ${ADJUSTMENT_COLUMNS}`,
    [
      p.id,
      p.businessId,
      p.bucket,
      p.unitsDelta,
      p.reasonCode ?? null,
      p.reasonText,
      p.reference,
      p.createdBy,
      p.ledgerEntryId,
      p.idempotencyKey,
      p.correlationId,
    ],
  );
  return mapAdjustment(result.rows[0]);
}

export async function listManualAdjustments(
  db: Queryable,
  businessId: string,
): Promise<CommercialManualAdjustment[]> {
  const result = await db.query<AdjustmentRow>(
    `SELECT ${ADJUSTMENT_COLUMNS} FROM commercial_manual_adjustments
      WHERE business_id = $1 ORDER BY created_at, id`,
    [businessId],
  );
  return result.rows.map(mapAdjustment);
}
